### ISSUE TITLE
Karim's sprint retrospective

### ISSUE THREAD

**Issue by karimassi** [karimassi/balelec-bud#122]
As I won't be able to attend this Friday's meeting, I will debrief my side of the past three weeks in the following. We chose to run 3 sprints (including one during the easter break) to keep the same pace. 

### Sprint 6 (03.04 - 10.04)
- Mocked the HttpClient (#90) used for retrieving the realtime transport information 

### Sprint 7 (10.04 - 17.04)
- Updated the Point of Interest GUI (#107) to show the amount of people near a GUI. @axelmarmet helped me on this one,  since he wrote the querying logic. Firestore only allows querying on one field, so it is not possible to query both latitude and longitude: we need an ordered metric to represent locations. We had to use an [external library](https://github.com/mbramwell1/GeoFire-Android) to query documents near a location: it is based on geohashes. 
- Migrated from Google Maps to MapBox (#112) for better flexibility when using custom markers, or in the event a fully customised map is needed. It also allows for offline access   

### Sprint 8 (17.04 - 14.04)
- Displayed the POI on the map (#120) with a custom marker. Added types to POI to distinguish different interests (allows filtering interests in the future).

### General Comments 
- We noticed there was a lack of team effort in the group. This issue was tackled during our daily scrums, and we have been working on it so far. 

See you next week !

**Comment by rishabh246** [comment]
Thanks for the retrospective. 
Good job on the POI and the live transport info. 

For next week, your currently assigned task is a little vague. Please take a look at https://github.com/karimassi/balelec-bud/issues/82 to see our thoughts on this.
